### ISSUE TITLE
how to use other middleware

### ISSUE THREAD

**Issue by subnetsix** [mnabialek/laravel-modular#10]
How do I use the modular with parent middleware?
such as
Route::group([
    //'middleware' => 'access.routeNeedsPermission:manage-announcements',
], function () {
    Route::resource('announcements', 'AnnouncementController');

});

**Comment by mnabialek** [comment]
You can use middlewares as you showed above. In many projects I use them like this:

```php
Route::group(['middleware' => 'api_guest'], function () {
    Route::put('companies/invitations/accept', 'InvitationController@accept');
    Route::put('companies/invitations/reject', 'InvitationController@reject');
});
```

and it's working without any problem.
