### ISSUE TITLE
how to returning view on modular modules

### ISSUE THREAD

**Issue by aiqbalsyah** [mnabialek/laravel-modular#12]
I've made a module inventory. how do I bring up the view that in the folder module inventory..
Big Thanks

**Comment by mnabialek** [comment]
Sorry for long response. In each module you can create service provider, where you can use:

    $this->loadViewsFrom(__DIR__.'/path/to/views', 'inventory');

and later in your code to render view you need to use it like so:

    inventory::yourview

to render view as described here https://laravel.com/docs/5.4/packages#views
