### ISSUE TITLE
Problem with Route service

### ISSUE THREAD

**Issue by bashet** [mnabialek/laravel-modular#2]
I have added this project exactly as described, but there was problem with routing service. I had to make following changes to make it work.
# I have addedd following code at the end of the map function in RouteServiceProvider (instead of instructed code):

<pre>
Route::group([
            'namespace' => 'App\Modules', // this initail namespace upto Modules
        ], function () {
            foreach (glob(app_path().'/Modules/*/routes/*.php') as $filename) { // this will include any php file in routes directory under created module
                require_once($filename);
            }
});
</pre>
# I changed the code as below in web.php in testmodule routes directory

<pre>
Route::group([
    'namespace' => 'TestModule\Http\Controllers', // module specifc namespace
    'middleware' => ['web']
],function () {
    Route::resource('testmodules', 'TestModuleController');
});
</pre>
# I hope this will be helpful of others

**Comment by mnabialek** [comment]
What branch are you using? Today I've published v0.2.1 which fixed one routing error. However it seems you are using routing in wrong way.  In `RouteServiceProvider` for 0.2.\* according to readme, you should only use by default:

```
\Modular::loadRoutes($this->app['router'], 'web');
\Modular::loadRoutes($this->app['router'], 'api');
```

without adding any namespaces here. Namespaces are applied automatically by `loadRoutes` method and you shouldn't use them manually
