### ISSUE TITLE
Duplicated directory created for make-migration command

### ISSUE THREAD

**Issue by bashet** [mnabialek/laravel-modular#3]
I tried to create a new table in my Product module where there is another table already exist! I run the command as below and full directory structure has been created in my product module. But this should be created only migration file as the Product module already there with right structure!

<pre>
vagrant@homestead:~/Code/order$ php artisan module:make-migration Product create_product_attributes_table --table=ProductAttribute --type=create
[Module Product] Created directory app/Modules/Product/Database/Migrations
[Module Product] Created file app/Modules/Product/Database/Migrations/2016_08_30_012731_create_product_attributes_table.php
[Module Product] Created migration file: 2016_08_30_012731_create_product_attributes_table.php
</pre>

**Comment by bashet** [comment]
I made a pull request which will fix this issue. Please check. @mnabialek

**Comment by mnabialek** [comment]
Are you sure you already had `app/Modules/Product/Database/Migrations` directory? By default all commands verify if directory already exists and if it's not, it will be created. For each created directory/file you should get info on console as above. I suppose you might have changed something in your config, but you haven't set `module.migrations.path` to valid directory in `modular.php` file
