### ISSUE TITLE
How to create seprate middleware in Module?

### ISSUE THREAD

**Issue by anosim** [mnabialek/laravel-modular#8]
this is really helpful package but i want to know how to add middleware separately in module?

for example i create ACL Module and i need middleware there Roles, Permissions.

i want to take all middleware separately.

if you can help me about that.

**Comment by mnabialek** [comment]
You can create files in each module as in normal PHP project so you can create in Module ACL directory Middleware and put there your middlewares in there and then in `app/Http/Kernel.php` you can add them and use them in any routes/controllers you want. If you need to create many middlewares you can also create stubs for middlewares in `modular.php` config file and then you can create middleware templates like so:

```
artisan module:files ACL Role --group=middleware
```

If you need to use permission based authorization you can also look at some ready packages or my https://github.com/mnabialek/laravel-authorize package
